//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.06 at 05:26:30 PM MESZ 
//


package org.deegree.services.wpvs.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.deegree.commons.configuration.BoundingBoxType;
import org.deegree.commons.configuration.KeywordsType;
import org.deegree.commons.configuration.ScaleDenominatorsType;


/**
 * 
 *         A data type defines some properties like name, title and descriptions. A data type can have a bounding box, defining it's validity. The scale
 *         denominators are used to define the scales for which a data instance is valid.
 *       
 * 
 * <p>Java class for AbstractDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MetadataURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/commons}Keywords" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/commons}BoundingBox" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/commons}ScaleDenominators" minOccurs="0"/>
 *         &lt;element name="MaxPixelError" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDataType", propOrder = {
    "name",
    "title",
    "metadataURL",
    "_abstract",
    "keywords",
    "boundingBox",
    "scaleDenominators",
    "maxPixelError"
})
@XmlSeeAlso({
    AbstractFeatureDatasetType.class,
    DEMTextureDataset.class,
    ElevationDataset.class
})
public abstract class AbstractDataType {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "MetadataURL")
    protected List<String> metadataURL;
    @XmlElement(name = "Abstract")
    protected String _abstract;
    @XmlElement(name = "Keywords", namespace = "http://www.deegree.org/commons")
    protected List<KeywordsType> keywords;
    @XmlElement(name = "BoundingBox", namespace = "http://www.deegree.org/commons")
    protected BoundingBoxType boundingBox;
    @XmlElement(name = "ScaleDenominators", namespace = "http://www.deegree.org/commons")
    protected ScaleDenominatorsType scaleDenominators;
    @XmlElement(name = "MaxPixelError", defaultValue = "5.0")
    protected Double maxPixelError;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the metadataURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMetadataURL() {
        if (metadataURL == null) {
            metadataURL = new ArrayList<String>();
        }
        return this.metadataURL;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordsType }
     * 
     * 
     */
    public List<KeywordsType> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<KeywordsType>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link BoundingBoxType }
     *     
     */
    public BoundingBoxType getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoundingBoxType }
     *     
     */
    public void setBoundingBox(BoundingBoxType value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the scaleDenominators property.
     * 
     * @return
     *     possible object is
     *     {@link ScaleDenominatorsType }
     *     
     */
    public ScaleDenominatorsType getScaleDenominators() {
        return scaleDenominators;
    }

    /**
     * Sets the value of the scaleDenominators property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScaleDenominatorsType }
     *     
     */
    public void setScaleDenominators(ScaleDenominatorsType value) {
        this.scaleDenominators = value;
    }

    /**
     * Gets the value of the maxPixelError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPixelError() {
        return maxPixelError;
    }

    /**
     * Sets the value of the maxPixelError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPixelError(Double value) {
        this.maxPixelError = value;
    }

}
