//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.06 at 05:26:30 PM MESZ 
//


package org.deegree.services.wpvs.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.deegree.commons.datasource.configuration.MultiResolutionDataSource;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wpvs}AbstractDataType">
 *       &lt;sequence>
 *         &lt;element name="MaxProjectedTexelSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/datasource}MultiResolutionDataSource"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxProjectedTexelSize",
    "multiResolutionDataSource"
})
@XmlRootElement(name = "DEMTextureDataset")
public class DEMTextureDataset
    extends AbstractDataType
{

    @XmlElement(name = "MaxProjectedTexelSize", defaultValue = "5.0")
    protected Double maxProjectedTexelSize;
    @XmlElement(name = "MultiResolutionDataSource", namespace = "http://www.deegree.org/datasource", required = true)
    protected MultiResolutionDataSource multiResolutionDataSource;

    /**
     * Gets the value of the maxProjectedTexelSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxProjectedTexelSize() {
        return maxProjectedTexelSize;
    }

    /**
     * Sets the value of the maxProjectedTexelSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxProjectedTexelSize(Double value) {
        this.maxProjectedTexelSize = value;
    }

    /**
     * Gets the value of the multiResolutionDataSource property.
     * 
     * @return
     *     possible object is
     *     {@link MultiResolutionDataSource }
     *     
     */
    public MultiResolutionDataSource getMultiResolutionDataSource() {
        return multiResolutionDataSource;
    }

    /**
     * Sets the value of the multiResolutionDataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiResolutionDataSource }
     *     
     */
    public void setMultiResolutionDataSource(MultiResolutionDataSource value) {
        this.multiResolutionDataSource = value;
    }

}
